# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mumuk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftSoup'
  # Pods for mumuk

  target 'mumukTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mumukUITests' do
    # Pods for testing
  end
pod 'NMapsMap'

end
